[project]
name = "parasite-research-nft"
description = "NFT Marketplace for Parasitology Research"
authors = ["Your Name <your.email@example.com>"]
telemetry = true
cache_dir = "./.clarinet"

[contracts]
parasite-nft = { path = "contracts/parasite-nft.clar" }
marketplace = { path = "contracts/marketplace.clar" }
research-access = { path = "contracts/research-access.clar" }
nft-trait = { path = "contracts/nft-trait.clar" }

[repl.analysis]
passes = ["check_checker"]

[repl]
cost_model = "v1"
